"""H1 offline wire-contract regressions. No Archicad import/socket is allowed.

Golden schema is transcribed from c55f404's T1/T2 helpers, NOT generated by the
shared builder and NOT new live evidence. The command spy uses the AC29 API
shape (no official GetProjectInfo/GetDetailsOfElements). Existing test_p0's
synthetic capability fixture is reused only for Executor PRECHECK tests; no
capability report or production permission is produced here.
"""
from __future__ import annotations

import copy
from functools import wraps
import json
from pathlib import Path
import sys
import tempfile
from types import SimpleNamespace
import unittest.mock as mock
import uuid

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "reference"))
sys.path.insert(0, str(ROOT / "probes"))

from bimexec.adapters import AdapterError, ExecutorAdapter
from bimexec.executor import Executor
from bimexec.tapir_raw import TapirRaw, AdapterUnavailable
from backends_v13 import TapirBackendV13
import ac29_contract as contract
import probe_t2_live_v13 as t1
import probe_t2_connections_v13 as t2
from tests.test_probe_v13 import FakeTypes as PropertyTypes

PROJECT = r"C:\Users\Admin\Downloads\MCP_TEST.pln"
GUID = "A0159B37-5EA0-48BB-A8C4-4DDE446DAF61"
NEW_GUID = "00000000-0000-0000-0000-000000000001"
COMPOSITE = "29EE690D-089C-4573-94C8-DEC75CFA0950"
LAYER = "Конструктив - Несущие Элементы"
STORY = {"name": "Первый Этаж", "elevation": 0.0}
GOLDEN = {"wallsData": [{
    "begCoordinate": {"x": 1.5, "y": 2.5},
    "endCoordinate": {"x": 6.5, "y": 2.5},
    "floorIndex": 0, "zCoordinate": 0.0, "height": 3.0, "thickness": 0.30,
    "offset": 0.0, "arcAngle": 0.0, "referenceLineLocation": "CoreOutside",
    "structureType": "Composite", "compositeId": {"guid": COMPOSITE},
}]}

TESTS = []


def test(fn):
    @wraps(fn)
    def offline():
        with mock.patch("socket.socket", side_effect=AssertionError("H1 must be offline")):
            return fn()
    TESTS.append((fn.__name__, offline))
    return offline


def refusal(fn):
    try:
        fn()
    except AdapterError:
        return
    raise AssertionError("expected a typed AdapterError, not success/0/None")


class Types(PropertyTypes):
    class AddOnCommandId:
        def __init__(self, namespace, command):
            self.namespace, self.command = namespace, command


class Commands:
    def __init__(self):
        self.reads, self.writes = [], []
        self.responses = {
            "GetProjectInfo": {"projectPath": PROJECT, "projectName": "MCP_TEST", "isUntitled": False, "isTeamwork": False},
            "GetAddOnVersion": {"version": "1.5.9"},
            "GetStories": {"stories": [{"index": 0, "name": STORY["name"], "level": 0.0}]},
            "GetElementsByType": {"elements": [{"elementId": {"guid": GUID}}]},
            "GetDetailsOfElements": {"detailsOfElements": [json.loads(
                (ROOT / "results/capability_matrix_v13_2.json").read_text(encoding="utf-8"))
                ["raw_dumps"]["GetDetailsOfElements_sample"]]},
            "CreateWalls": {"elements": [{"elementId": {"guid": NEW_GUID}}]},
        }
        self.all_response = [{"elementId": {"guid": GUID}}]
        self.product_unavailable = False

    def GetProductInfo(self):
        if self.product_unavailable:
            raise AttributeError("optional product info unavailable")
        return {"version": 29, "buildNumber": 3000}

    def GetAllElements(self):
        self.reads.append(("official.GetAllElements", {}))
        if isinstance(self.all_response, Exception):
            raise self.all_response
        return copy.deepcopy(self.all_response)

    def ExecuteAddOnCommand(self, command_id, payload):
        assert command_id.namespace == "TapirCommand"
        name = command_id.command
        record = (name, copy.deepcopy(payload))
        (self.writes if name == "CreateWalls" else self.reads).append(record)
        response = self.responses[name]
        if isinstance(response, Exception):
            raise response
        return copy.deepcopy(response)

    def SetPropertyValuesOfElements(self, items):
        self.writes.append(("official.SetPropertyValuesOfElements", items))
        return []


class Utilities:
    def __init__(self):
        self.mode = "ok"

    def GetBuiltInPropertyId(self, name):
        return ("builtin", name)

    def GetPropertyValuesDictionary(self, elements, pids):
        if self.mode == "raise":
            raise TimeoutError("property read failed")
        if self.mode == "missing":
            return {}
        if self.mode == "wrong_property":
            return {e: {("unrelated", "property"): "wrong value"} for e in elements}
        value = LAYER if pids[0][1] == "ModelView_LayerName" else "ПЕР - 005"
        if self.mode == "none":
            value = None
        return {e: {pids[0]: value} for e in elements}


def make(*, expected_project=PROJECT):
    commands, utilities = Commands(), Utilities()
    backend = TapirBackendV13(port=19723, types=("Wall",))
    backend.conn = SimpleNamespace(commands=commands, utilities=utilities, types=Types())
    raw = TapirRaw(port=19723, types=("Wall",), expected_project=expected_project, backend=backend)
    return raw, commands, utilities


def wall():
    return {"story": dict(STORY), "layer": LAYER, "from": [1.5, 2.5], "to": [6.5, 2.5],
            "height": 3.0, "thickness": 0.30, "reference_line": "CoreOutside",
            "structure_type": "Composite", "composite_id": COMPOSITE, "base_level": 0.0}


@test
def h1_runtime_and_t1_t2_share_frozen_live_wall_schema():
    raw, commands, _ = make()
    result = ExecutorAdapter(raw, "element_id").create_wall(wall())
    assert result.candidate_guid == NEW_GUID
    assert commands.writes == [("CreateWalls", GOLDEN)]
    assert t1.payload(COMPOSITE) == GOLDEN
    segment = {"from_abs": (1.5, 2.5), "to_abs": (6.5, 2.5)}
    assert t2.wall_payload(segment, COMPOSITE) == GOLDEN
    assert t1.create_once(raw.backend, GOLDEN) == [NEW_GUID]
    assert t2.create_once(raw.backend, GOLDEN) == [NEW_GUID]
    assert commands.writes == [("CreateWalls", GOLDEN)] * 3


@test
def h1_all_six_t2_segments_use_same_complete_schema():
    for seg in t2.abs_segments((0.0, 0.0)):
        expected = copy.deepcopy(GOLDEN)
        expected["wallsData"][0]["begCoordinate"] = dict(zip(("x", "y"), seg["from_abs"]))
        expected["wallsData"][0]["endCoordinate"] = dict(zip(("x", "y"), seg["to_abs"]))
        raw, commands, _ = make()
        op = wall()
        op.update({"from": list(seg["from_abs"]), "to": list(seg["to_abs"])})
        ExecutorAdapter(raw, "element_id").create_wall(op)
        assert commands.writes == [("CreateWalls", expected)]
        assert t2.wall_payload(seg, COMPOSITE) == expected


@test
def h1_tapir_read_attribution_and_live_details_normalization():
    raw, commands, _ = make()
    assert not hasattr(commands, "GetProjectInfo")
    assert not hasattr(commands, "GetDetailsOfElements")
    assert raw.project_info()["project_path"] == PROJECT
    d = ExecutorAdapter(raw, "element_id").get_details(GUID)
    assert d["story"] == STORY and d["layer"] == LAYER
    assert d["height"] == 3.0 and d["thickness"] == 0.3
    assert d["ref_line"] == {"from": [-82.103501371, 30.243410145], "to": [-73.173380027, 30.243410145]}
    assert d == t2.observe(raw.backend, GUID, raw.stories())
    details_calls = [p for name, p in commands.reads if name == "GetDetailsOfElements"]
    assert details_calls and all(p == {"elements": [{"elementId": {"guid": GUID}}]} for p in details_calls)
    assert commands.writes == []


@test
def h1_optional_product_info_is_not_project_discovery():
    raw, commands, _ = make()
    commands.product_unavailable = True
    info = raw.project_info()
    assert info["project_name"] == "MCP_TEST" and info["archicad_version"] == ""
    assert commands.writes == []


@test
def h1_only_explicit_empty_count_is_zero():
    raw, commands, _ = make()
    for response in ([], {"elements": []}):
        commands.responses["GetElementsByType"] = response
        assert raw.count_by_type() == {"Wall": 0}
    commands.responses["GetElementsByType"] = {
        "elements": [SimpleNamespace(elementId=SimpleNamespace(guid=uuid.UUID(GUID)))]}
    assert raw.count_by_type() == {"Wall": 1}  # official typed GUID form, not just JSON strings
    assert commands.writes == []


@test
def h1_count_transport_failure_raises_not_zero():
    raw, commands, _ = make()
    commands.responses["GetElementsByType"] = TimeoutError("no response")
    refusal(raw.count_by_type)
    assert commands.writes == []


@test
def h1_count_malformed_error_rows_and_empty_guids_raise():
    for response in (None, {}, {"error": "read failed"}, {"elements": None},
                     {"elements": [{"error": "not readable"}]},
                     {"elements": [{"elementId": {"guid": ""}}]},
                     {"elements": [{"elementId": {"guid": GUID}}] * 2}):
        raw, commands, _ = make()
        commands.responses["GetElementsByType"] = response
        refusal(raw.count_by_type)
        assert commands.writes == []


@test
def h1_failed_list_is_not_empty_or_negative_marker_search():
    for response in (None, {}, TimeoutError("list failed"), [{"error": "denied"}]):
        raw, commands, _ = make()
        commands.all_response = response
        refusal(raw.list_guids)
        refusal(lambda: raw.find_by_marker(exact="NOT_PRESENT"))
        assert commands.writes == []


@test
def h1_details_transport_failure_is_typed_unavailable():
    raw, commands, _ = make()
    commands.responses["GetDetailsOfElements"] = TimeoutError("details failed")
    refusal(lambda: ExecutorAdapter(raw, "element_id").get_details(GUID))
    refusal(lambda: raw.find_by_filter("Wall", STORY["name"], LAYER))
    assert commands.writes == []


@test
def h1_details_empty_error_unsupported_and_partial_are_not_absence():
    raw, commands, _ = make()
    original = commands.responses["GetDetailsOfElements"]
    missing_thickness = copy.deepcopy(original)
    del missing_thickness["detailsOfElements"][0]["details"]["begThickness"]
    for response in (None, {}, {"detailsOfElements": []},
                     {"detailsOfElements": [{"error": "Not yet supported element type"}]},
                     {"detailsOfElements": [{"type": "Wall", "details": {}}]}, missing_thickness):
        commands.responses["GetDetailsOfElements"] = response
        refusal(lambda: raw.details(GUID))
    assert commands.writes == []


@test
def h1_unavailable_properties_do_not_become_negative_scan():
    for mode in ("raise", "missing", "none", "wrong_property"):
        raw, commands, utilities = make()
        utilities.mode = mode
        refusal(lambda: raw.get_marker(GUID, "element_id"))
        refusal(lambda: raw.find_by_marker(prefix="BX:"))
        refusal(lambda: raw.details(GUID))
        assert commands.writes == []


@test
def h1_story_resolves_real_index_not_array_position_or_default_zero():
    raw, commands, _ = make()
    commands.responses["GetStories"] = {"stories": [
        {"index": 7, "name": "Upper", "level": 3.0},
        {"index": -2, "name": "Basement", "level": -6.0},
    ]}
    op = wall()
    op["story"] = {"name": "Basement", "elevation": -6.0}
    ExecutorAdapter(raw, "element_id").create_wall(op)
    expected = copy.deepcopy(GOLDEN)
    expected["wallsData"][0]["floorIndex"] = -2
    assert commands.writes == [("CreateWalls", expected)]


@test
def h1_unresolved_wrong_elevation_or_index_only_story_refuses_dispatch():
    for story in ({"name": "Absent", "elevation": 0.0}, {"name": STORY["name"], "elevation": 3.0},
                  {"name": STORY["name"]}, {"index": 0}, {"name": "", "elevation": 0.0}):
        raw, commands, _ = make()
        op = wall()
        op["story"] = story
        refusal(lambda: ExecutorAdapter(raw, "element_id").create_wall(op))
        assert commands.writes == []


@test
def h1_missing_duplicate_or_ambiguous_story_mapping_refuses_dispatch():
    for stories in ([], [{"name": STORY["name"], "level": 0.0}],
                    [{"index": 0, "name": STORY["name"], "level": 0.0}] * 2,
                    [{"index": i, "name": STORY["name"], "level": 0.0} for i in (0, 9)]):
        raw, commands, _ = make()
        commands.responses["GetStories"] = {"stories": stories}
        refusal(lambda: raw.create_wall(wall()))
        assert commands.writes == []


@test
def h1_story_read_failure_and_contradictory_explicit_index_refuse_dispatch():
    raw, commands, _ = make()
    op = wall()
    op["story_index"] = 12
    refusal(lambda: ExecutorAdapter(raw, "element_id").create_wall(op))
    commands.responses["GetStories"] = TimeoutError("stories failed")
    refusal(lambda: raw.create_wall(wall()))
    assert commands.writes == []


@test
def h1_wrong_project_untitled_teamwork_and_unknown_flags_refuse_all_writes():
    for change in ({"projectPath": r"C:\other.pln"}, {"isUntitled": True},
                   {"isTeamwork": True}, {"isTeamwork": None}, {"projectName": ""}):
        raw, commands, _ = make()
        commands.responses["GetProjectInfo"].update(change)
        refusal(raw.project_info)
        refusal(lambda: ExecutorAdapter(raw, "element_id").create_wall(wall()))
        refusal(lambda: raw.set_marker(GUID, "BX:TEST", "element_id"))
        assert commands.writes == []


@test
def h1_unconfigured_project_or_wrong_addon_cannot_write():
    raw, commands, _ = make(expected_project=None)
    refusal(lambda: raw.create_wall(wall()))
    assert commands.writes == []
    for version in ("1.5.8", "", None):
        raw, commands, _ = make()
        commands.responses["GetAddOnVersion"] = {"version": version}
        refusal(lambda: raw.create_wall(wall()))
        assert commands.writes == []


@test
def h1_no_defaults_for_composite_reference_line_or_new_wall_semantics():
    for change in ({"reference_line": "center"}, {"structure_type": "Basic"},
                   {"height": 4.0}, {"thickness": 0.2}, {"composite_id": ""},
                   {"top_link": "absolute"}, {"base_level": 1.0}, {"arc_angle": 0.5}):
        raw, commands, _ = make()
        op = wall()
        op.update(change)
        refusal(lambda: ExecutorAdapter(raw, "element_id").create_wall(op))
        assert commands.writes == []
    for key in ("composite_id", "structure_type", "reference_line", "story"):
        raw, commands, _ = make()
        op = wall()
        del op[key]
        refusal(lambda: ExecutorAdapter(raw, "element_id").create_wall(op))
        assert commands.writes == []


@test
def h1_adapter_forwards_only_explicit_fields_no_story_index_default():
    class RawSpy:
        def create_wall(self, params):
            self.params = params
            return NEW_GUID
    spy = RawSpy()
    ExecutorAdapter(spy, "element_id").create_wall(wall())
    assert "story_index" not in spy.params
    assert spy.params["composite_id"] == COMPOSITE
    assert spy.params["reference_line"] == "CoreOutside"


@test
def h1_failed_write_response_is_typed_unknown_and_never_retried():
    for response in (TimeoutError("lost response"), {"elements": []}, {"error": "failed"}):
        raw, commands, _ = make()
        commands.responses["CreateWalls"] = response
        refusal(lambda: raw.create_wall(wall()))
        assert commands.writes == [("CreateWalls", GOLDEN)]


@test
def h1_read_inventory_does_not_probe_by_writing():
    raw, commands, _ = make()
    names = raw.available_commands()
    assert {"GetProjectInfo", "GetDetailsOfElements", "GetStories"} <= names
    assert "CreateWalls" not in names
    assert commands.writes == []


@test
def h1_t0_mutation_denylist_not_widened():
    raw, commands, _ = make()
    try:
        raw.backend._tapir("CreateWalls")
    except Exception:
        pass
    else:
        raise AssertionError("T0 denylist was widened")
    assert commands.writes == []


@test
def h1_executor_count_or_details_failed_precheck_never_dispatches():
    from tests.test_p0 import cap_matrix, plan
    for failed_command in ("GetElementsByType", "GetDetailsOfElements"):
        raw, commands, _ = make()
        with tempfile.TemporaryDirectory() as d:
            ex = Executor(ExecutorAdapter(raw, "element_id"), cap_matrix(), str(Path(d) / "j.jsonl"), write_gate=True)
            ex.confirm_token = "existing-offline-test-fixture-only"
            p = plan()
            op = p["packages"][0]["operations"][0]
            op.update(wall())
            op.pop("top_link", None)
            op["verify"]["story"] = dict(STORY)
            op["verify"]["layer"] = LAYER
            try:
                ex.submit(p)
                commands.responses[failed_command] = TimeoutError("failed precheck")
                refusal(ex.run)
                assert commands.writes == []
            finally:
                ex.close()


@test
def h1_executor_project_drift_precheck_never_dispatches():
    from tests.test_p0 import cap_matrix, plan
    raw, commands, _ = make()
    with tempfile.TemporaryDirectory() as d:
        ex = Executor(ExecutorAdapter(raw, "element_id"), cap_matrix(), str(Path(d) / "j.jsonl"), write_gate=True)
        ex.confirm_token = "existing-offline-test-fixture-only"
        try:
            ex.submit(plan())
            commands.responses["GetProjectInfo"]["projectPath"] = r"C:\other.pln"
            assert ex.run().value == "PAUSED"
            assert commands.writes == []
        finally:
            ex.close()


if __name__ == "__main__":
    failed = 0
    for name, fn in TESTS:
        try:
            fn()
            print("PASS", name)
        except Exception:
            failed += 1
            import traceback
            traceback.print_exc()
            print("FAIL", name)
    print(f"H1: {len(TESTS) - failed} PASS, {failed} failures")
    raise SystemExit(bool(failed))
