from __future__ import annotations

import json
import urllib.request
from pathlib import Path
from typing import Any

BRIDGE = "http://127.0.0.1:19723"
LIBPART_NAME = "SB_Gothic_Lancet_Large_v01"
STATE_FILE = Path("gothic_tower_top_stage_state.json")
PILOT_STATE = Path("true_gothic_window_pilot_state.json")
WALL_STATE_KEY = "WALL:SIDE_0"

A = 1.48
B = 4.32
SILL = 2.00
CENTER_OFFSET = 2.50

# A real Window Library Part: WALLHOLE is inside the Window's own 3D GDL.
# This first pilot intentionally keeps the frame geometry simple; the acceptance
# gate is semantic correctness (Archicad type Window + hosted wall + libpart).
SCRIPT_3D = r'''
! SAFE BIM Gothic Lancet Window v01
! True hosted Window: the opening shape is generated by WALLHOLE.

fw = 0.12
spring = B * 0.62
depth = WALL_THICKNESS

! Pointed custom wall opening. If WALLHOLE is present Archicad does not create
! the default rectangular opening for this Window.
WALLHOLE 7, 1,
    -A/2,      0,          15,
     A/2,      0,          15,
     A/2,      spring,     15,
     A*0.30,   B*0.83,     15,
     0,        B,          15,
    -A*0.30,   B*0.83,     15,
    -A/2,      spring,     15

! Stone/frame bodies occupy the opening itself; everything remains one Window.
MATERIAL WALL_MAT_EDGE

! sill
PRISM_ 4, depth,
    -A/2, 0,        15,
     A/2, 0,        15,
     A/2, fw,       15,
    -A/2, fw,       15

! left jamb
PRISM_ 4, depth,
    -A/2,      fw,      15,
    -A/2+fw,   fw,      15,
    -A/2+fw,   spring,  15,
    -A/2,      spring,  15

! right jamb
PRISM_ 4, depth,
     A/2-fw,   fw,      15,
     A/2,      fw,      15,
     A/2,      spring,  15,
     A/2-fw,   spring,  15

! pointed archivolt, four trapezoidal segments
PRISM_ 4, depth,
    -A/2,       spring,          15,
    -A*0.30,    B*0.83,         15,
    -A*0.30+fw, B*0.83-fw*0.45, 15,
    -A/2+fw,    spring,          15

PRISM_ 4, depth,
    -A*0.30,       B*0.83,          15,
     0,            B,               15,
     0,            B-fw*1.15,       15,
    -A*0.30+fw,    B*0.83-fw*0.45,  15

PRISM_ 4, depth,
     0,            B,               15,
     A*0.30,       B*0.83,          15,
     A*0.30-fw,    B*0.83-fw*0.45,  15,
     0,            B-fw*1.15,       15

PRISM_ 4, depth,
     A*0.30,    B*0.83,         15,
     A/2,       spring,          15,
     A/2-fw,    spring,          15,
     A*0.30-fw, B*0.83-fw*0.45, 15

! central mullion
mw = 0.065
PRISM_ 4, depth,
    -mw/2, fw,          15,
     mw/2, fw,          15,
     mw/2, B*0.71,      15,
    -mw/2, B*0.71,      15

! glazing: thin body in the middle of the wall
ADDZ depth/2 - 0.01
MATERIAL 0
PRISM_ 7, 0.02,
    -A/2+fw,       fw,                15,
     A/2-fw,       fw,                15,
     A/2-fw,       spring,            15,
     A*0.30-fw,    B*0.83-fw*0.45,    15,
     0,            B-fw*1.15,         15,
    -A*0.30+fw,    B*0.83-fw*0.45,    15,
    -A/2+fw,       spring,            15
DEL 1
'''.strip() + "\n"

SCRIPT_2D = r'''
! Minimal clean plan symbol for the pilot.
PEN 1
LINE2 -A/2, 0, A/2, 0
LINE2 -A/2, WALL_THICKNESS/2, A/2, WALL_THICKNESS/2
'''.strip() + "\n"


def call(command: str, params: dict[str, Any]) -> dict[str, Any]:
    payload = {
        "command": "API.ExecuteAddOnCommand",
        "parameters": {
            "addOnCommandId": {
                "commandNamespace": "TapirCommand",
                "commandName": command,
            },
            "addOnCommandParameters": params,
        },
    }
    request = urllib.request.Request(
        BRIDGE,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=180) as response:
        return json.loads(response.read().decode("utf-8"))


def response_body(response: dict[str, Any]) -> dict[str, Any]:
    value = response.get("result", {}).get("addOnCommandResponse", {})
    return value if isinstance(value, dict) else {}


def command_error(response: dict[str, Any]) -> Any:
    if "error" in response:
        return response["error"]
    body = response_body(response)
    if "error" in body:
        return body["error"]
    return None


def read_one(guid: str) -> dict[str, Any]:
    response = call(
        "GetDetailsOfElements",
        {"elements": [{"elementId": {"guid": guid}}]},
    )
    rows = response_body(response).get("detailsOfElements", [])
    if len(rows) != 1:
        raise RuntimeError(f"read-back expected one element, got {len(rows)}")
    return rows[0]


def load_wall_guid() -> str:
    state = json.loads(STATE_FILE.read_text(encoding="utf-8"))
    entry = state.get("steps", {}).get(WALL_STATE_KEY)
    if not isinstance(entry, dict) or not entry.get("guid"):
        raise RuntimeError(f"No GUID for {WALL_STATE_KEY} in {STATE_FILE}")
    return str(entry["guid"])


def created_guid(response: dict[str, Any]) -> str:
    rows = response_body(response).get("elements", [])
    errors = [row.get("error") for row in rows if isinstance(row, dict) and row.get("error")]
    if errors:
        raise RuntimeError("CreateWindows error:\n" + json.dumps(errors, ensure_ascii=False, indent=2))
    guids = []
    for row in rows:
        try:
            guids.append(row["elementId"]["guid"])
        except Exception:
            pass
    if len(guids) != 1:
        raise RuntimeError(f"Expected one created Window GUID, got {guids}")
    return guids[0]


def validate_window(guid: str, wall_guid: str) -> dict[str, Any]:
    row = read_one(guid)
    if row.get("type") != "Window":
        raise RuntimeError(f"Semantic gate failed: {guid} is {row.get('type')!r}, not Window")

    details = row.get("details", {})
    owner = details.get("ownerElementId", {}).get("guid")
    if owner != wall_guid:
        raise RuntimeError(f"Owner gate failed: expected {wall_guid}, got {owner}")

    lib = details.get("libPart", {})
    actual_name = lib.get("name") or lib.get("documentName")
    if actual_name != LIBPART_NAME:
        raise RuntimeError(
            f"Library Part gate failed: expected {LIBPART_NAME!r}, got {actual_name!r}; libPart={lib!r}"
        )
    return row


def main() -> int:
    if not STATE_FILE.exists():
        raise RuntimeError(f"Tower state not found: {STATE_FILE.resolve()}")

    wall_guid = load_wall_guid()
    wall = read_one(wall_guid)
    if wall.get("type") != "Wall":
        raise RuntimeError(f"Host {wall_guid} is {wall.get('type')}, not Wall")

    # Idempotent pilot: if a previous PASS exists, verify the exact same Window
    # instead of creating a duplicate.
    if PILOT_STATE.exists():
        previous = json.loads(PILOT_STATE.read_text(encoding="utf-8"))
        guid = previous.get("windowGuid")
        if guid:
            validate_window(str(guid), wall_guid)
            print("Existing pilot Window re-verified:", guid)
            return 0

    print("===== 1. CREATE / ENSURE REAL WINDOW LIBRARY PART =====")
    create_part = call(
        "CreateLibraryPartFromScripts",
        {
            "type": "Window",
            "name": LIBPART_NAME,
            "a": A,
            "b": B,
            "script2D": SCRIPT_2D,
            "script3D": SCRIPT_3D,
            "returnExisting": True,
        },
    )
    if command_error(create_part):
        raise RuntimeError(
            "CreateLibraryPartFromScripts failed:\n"
            + json.dumps(create_part, ensure_ascii=False, indent=2)
        )
    print(json.dumps(response_body(create_part), ensure_ascii=False, indent=2))

    # Reload is intentionally explicit so GetAvailableLibraryParts and the
    # subsequent CreateWindows resolve against the same refreshed registry.
    reload_response = call("ReloadLibraries", {})
    if command_error(reload_response):
        raise RuntimeError("ReloadLibraries failed: " + json.dumps(reload_response, ensure_ascii=False))

    inventory = call("GetAvailableLibraryParts", {"filterByTypeId": "Window"})
    parts = response_body(inventory).get("libraryParts", [])
    matching = [p for p in parts if str(p.get("documentName", "")) == LIBPART_NAME]
    if len(matching) != 1:
        raise RuntimeError(
            f"Library inventory gate failed: expected exactly one {LIBPART_NAME!r}, found {len(matching)}. "
            f"Window inventory count={len(parts)}"
        )
    print("[PASS] Window Library Part registered:", matching[0])

    print("===== 2. CREATE ONE TRUE HOSTED WINDOW =====")
    create_window = call(
        "CreateWindows",
        {
            "windowsData": [
                {
                    "ownerWallId": {"guid": wall_guid},
                    "centerOffset": CENTER_OFFSET,
                    "sillHeight": SILL,
                    "width": A,
                    "height": B,
                    "libraryPartName": LIBPART_NAME,
                }
            ]
        },
    )
    guid = created_guid(create_window)
    row = validate_window(guid, wall_guid)

    PILOT_STATE.write_text(
        json.dumps(
            {
                "windowGuid": guid,
                "wallGuid": wall_guid,
                "libraryPartName": LIBPART_NAME,
                "semanticType": row.get("type"),
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    print()
    print("========================================")
    print("TRUE GOTHIC WINDOW PILOT: PASS")
    print("========================================")
    print("GUID:", guid)
    print("Archicad type: Window")
    print("Hosted wall:", wall_guid)
    print("Library Part:", LIBPART_NAME)
    print()
    print("Morph prototypes were NOT deleted. Inspect this one Window in 3D/plan first.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
